services:
  localstack:
    image: localstack/snowflake:2026.06.0
    container_name: localstack-main
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:443:443'
      - '127.0.0.1:4510-4560:4510-4560'
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - PERSISTENCE=1
    volumes:
      - './volume:/var/lib/localstack'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5
