[connections.snowflake]
account = "FGVTWTZ-YP96844"
user = "streamlit_svc"
private_key_file = "/Users/ernestviola/.snowflake/streamlit_key.p8"
role = "streamlit_role"
warehouse = "trading_pipeline_wh"
database = "trading_pipeline"
schema = "gold"