CREATE DATABASE IF NOT EXISTS TRADING_PIPELINE;
USE DATABASE TRADING_PIPELINE;

CREATE TABLE IF NOT EXISTS RAW_PRICES (
    symbol STRING,
    timestamp TIMESTAMP_TZ,
    open FLOAT,
    high FLOAT,
    low FLOAT,
    close FLOAT,
    volume FLOAT,
    trade_count FLOAT,
    vwap FLOAT
);

CREATE TABLE IF NOT EXISTS RAW_PRICES_STAGING LIKE RAW_PRICES;

CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE IF NOT EXISTS RAW_PRICES_STAGE
    FILE_FORMAT = CSV_FORMAT;

CREATE TABLE IF NOT EXISTS RAW_TRADES (
    SYMBOL STRING,
    "DATE" TIMESTAMP_TZ,
    PRICE FLOAT,
    HIGH FLOAT,
    LOW FLOAT,
    "CLOSE" FLOAT,
    VOLUME FLOAT,
    TRADE_COUNT FLOAT,
    VWAP FLOAT,
    ROLLING_MEAN FLOAT,
    ROLLING_STD FLOAT,
    Z_SCORE FLOAT,
    SIDE STRING,
    TICKER STRING,
    STRATEGY_USED STRING,
    QUANTITY FLOAT
);

CREATE TABLE IF NOT EXISTS RAW_TRADES_STAGING LIKE RAW_TRADES;

CREATE STAGE IF NOT EXISTS RAW_TRADES_STAGE
    FILE_FORMAT = CSV_FORMAT;